### ISSUE TITLE
[SETTING] Initial Project Setting

### ISSUE THREAD

**Issue by KimKwon** [Dagather/Dagather-Front#1]
# 초기 프로젝트 개발환경 세팅 

**javascript + React**

## 1. ESLint
```eslint``` 와 ```eslint-config-airbnb``` 적용.

코드의 질, 코드 스타일과 코드 가독성 등에 관련하여 코드 작성에 일정 제약을 주는 도구.

## 2. Prettier
> https://prettier.io/docs/en/options.html

vscode 사용 시  ```prettier extension```을 통해 코드 입력 스타일을 정해준다.

 ```json
// .prettierrc

{
  "singleQuote": true,
  "semi": true,
  "useTabs": false,
  "tabWidth": 2,
  "trailingComma": "all",
  "printWidth": 80
}

```

## 3. Sass
>  What is Sass?  https://poiemaweb.com/sass-basics 

```sass``` 를 통해 css 스타일링을 간결하고 가독성 좋은 문법으로 작성해보자.

```css
$pastel-pink: #FF6699;

.table {
  // .table__row
  &__row {
    background-color: $pastel-pink;
  }
  // .table__col
  &__col {
    background-color: blue;
  }
}

```

#### Components 
  - 각종 컴포넌트
#### Constants 
  - 각종 상수( 색상 값, 고정 문자열, 에러 메시지 등 ... )
#### Assets 
  - 프로젝트에서 사용하는 정적인 파일 (이미지, 폰트 등 ... )
#### Pages 
  - 라우팅을 통해 이동하게 될 페이지들

( 변경될 여지 다분함 )
